/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as examples from "./examples";
export type { examples };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Mailer } from "./Mailer";
export type { MockUSDC } from "./MockUSDC";
