[workspace]
members = [
    "programs/mail_service",
    "programs/mailer", 
    "programs/mail_box_factory"
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.30.1", features = ["derive"] }
anchor-spl = "0.30.1"