[workspace]
members = [
    "programs/mail_service",
    "programs/mailer", 
    "programs/mail_box_factory"
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.28.0", features = ["derive"] }
anchor-spl = "0.28.0"

[profile.release]
overflow-checks = true