/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMailerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "send"
      | "sendPrepared"
      | "sendPreparedToEmailAddress"
      | "sendThroughWebhook"
      | "sendToEmailAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "send",
    values: [AddressLike, string, string, AddressLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sendPrepared",
    values: [AddressLike, string, AddressLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sendPreparedToEmailAddress",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendThroughWebhook",
    values: [AddressLike, string, AddressLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sendToEmailAddress",
    values: [string, string, string, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendPrepared",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPreparedToEmailAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendThroughWebhook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendToEmailAddress",
    data: BytesLike
  ): Result;
}

export interface IMailer extends BaseContract {
  connect(runner?: ContractRunner | null): IMailer;
  waitForDeployment(): Promise<this>;

  interface: IMailerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  send: TypedContractMethod<
    [
      to: AddressLike,
      subject: string,
      body: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;

  sendPrepared: TypedContractMethod<
    [
      to: AddressLike,
      mailId: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;

  sendPreparedToEmailAddress: TypedContractMethod<
    [toEmail: string, mailId: string, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  sendThroughWebhook: TypedContractMethod<
    [
      to: AddressLike,
      webhookId: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;

  sendToEmailAddress: TypedContractMethod<
    [toEmail: string, subject: string, body: string, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [
      to: AddressLike,
      subject: string,
      body: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendPrepared"
  ): TypedContractMethod<
    [
      to: AddressLike,
      mailId: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendPreparedToEmailAddress"
  ): TypedContractMethod<
    [toEmail: string, mailId: string, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendThroughWebhook"
  ): TypedContractMethod<
    [
      to: AddressLike,
      webhookId: string,
      payer: AddressLike,
      revenueShareToReceiver: boolean,
      resolveSenderToName: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendToEmailAddress"
  ): TypedContractMethod<
    [toEmail: string, subject: string, body: string, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
