/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mailServiceSol from "./MailService.sol";
export * as mailerSol from "./Mailer.sol";
export { MockUSDC__factory } from "./MockUSDC__factory";
