/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mailServiceSol from "./MailService.sol";
export * as mailerSol from "./Mailer.sol";
export * as interfaces from "./interfaces";
export { MailBoxFactory__factory } from "./MailBoxFactory__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
