/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MailerIntegrationExampleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveUSDCForMailer"
      | "authorizeWithMailer"
      | "mailer"
      | "owner"
      | "sendEmailNotification"
      | "sendNotification"
      | "sendNotificationContractPays"
      | "sendPreparedContent"
      | "sendPriorityMessage"
      | "sendViaWebhook"
      | "usdcToken"
      | "withdrawUSDC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EmailNotificationSent" | "NotificationSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveUSDCForMailer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeWithMailer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mailer", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendEmailNotification",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendNotification",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendNotificationContractPays",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendPreparedContent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendPriorityMessage",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendViaWebhook",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDC",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "approveUSDCForMailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeWithMailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mailer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendEmailNotification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendNotification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendNotificationContractPays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPreparedContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPriorityMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendViaWebhook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDC",
    data: BytesLike
  ): Result;
}

export namespace EmailNotificationSentEvent {
  export type InputTuple = [email: string, message: string];
  export type OutputTuple = [email: string, message: string];
  export interface OutputObject {
    email: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NotificationSentEvent {
  export type InputTuple = [recipient: AddressLike, message: string];
  export type OutputTuple = [recipient: string, message: string];
  export interface OutputObject {
    recipient: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MailerIntegrationExample extends BaseContract {
  connect(runner?: ContractRunner | null): MailerIntegrationExample;
  waitForDeployment(): Promise<this>;

  interface: MailerIntegrationExampleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveUSDCForMailer: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizeWithMailer: TypedContractMethod<[], [void], "nonpayable">;

  mailer: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  sendEmailNotification: TypedContractMethod<
    [email: string, subject: string, body: string],
    [void],
    "nonpayable"
  >;

  sendNotification: TypedContractMethod<
    [recipient: AddressLike, message: string],
    [void],
    "nonpayable"
  >;

  sendNotificationContractPays: TypedContractMethod<
    [recipient: AddressLike, message: string],
    [void],
    "nonpayable"
  >;

  sendPreparedContent: TypedContractMethod<
    [recipient: AddressLike, mailId: string],
    [void],
    "nonpayable"
  >;

  sendPriorityMessage: TypedContractMethod<
    [recipient: AddressLike, subject: string, body: string],
    [void],
    "nonpayable"
  >;

  sendViaWebhook: TypedContractMethod<
    [recipient: AddressLike, webhookId: string],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  withdrawUSDC: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveUSDCForMailer"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeWithMailer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mailer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sendEmailNotification"
  ): TypedContractMethod<
    [email: string, subject: string, body: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendNotification"
  ): TypedContractMethod<
    [recipient: AddressLike, message: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendNotificationContractPays"
  ): TypedContractMethod<
    [recipient: AddressLike, message: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendPreparedContent"
  ): TypedContractMethod<
    [recipient: AddressLike, mailId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendPriorityMessage"
  ): TypedContractMethod<
    [recipient: AddressLike, subject: string, body: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendViaWebhook"
  ): TypedContractMethod<
    [recipient: AddressLike, webhookId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawUSDC"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EmailNotificationSent"
  ): TypedContractEvent<
    EmailNotificationSentEvent.InputTuple,
    EmailNotificationSentEvent.OutputTuple,
    EmailNotificationSentEvent.OutputObject
  >;
  getEvent(
    key: "NotificationSent"
  ): TypedContractEvent<
    NotificationSentEvent.InputTuple,
    NotificationSentEvent.OutputTuple,
    NotificationSentEvent.OutputObject
  >;

  filters: {
    "EmailNotificationSent(string,string)": TypedContractEvent<
      EmailNotificationSentEvent.InputTuple,
      EmailNotificationSentEvent.OutputTuple,
      EmailNotificationSentEvent.OutputObject
    >;
    EmailNotificationSent: TypedContractEvent<
      EmailNotificationSentEvent.InputTuple,
      EmailNotificationSentEvent.OutputTuple,
      EmailNotificationSentEvent.OutputObject
    >;

    "NotificationSent(address,string)": TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;
    NotificationSent: TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;
  };
}
