/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ISafe, ISafeInterface } from "../../MailService.sol/ISafe";

const _abi = [
  {
    inputs: [],
    name: "getThreshold",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISafe__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeInterface {
    return new Interface(_abi) as ISafeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISafe {
    return new Contract(address, _abi, runner) as unknown as ISafe;
  }
}
