/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MailService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MailService__factory>;
    getContractFactory(
      name: "MockSafe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSafe__factory>;
    getContractFactory(
      name: "MockUSDC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockUSDC__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "PrivilegedMail",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivilegedMail__factory>;
    getContractFactory(
      name: "IGnosisSafe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGnosisSafe__factory>;
    getContractFactory(
      name: "SafeChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeChecker__factory>;
    getContractFactory(
      name: "SafeDelegateHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeDelegateHelper__factory>;

    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MailService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MailService>;
    getContractAt(
      name: "MockSafe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSafe>;
    getContractAt(
      name: "MockUSDC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockUSDC>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "PrivilegedMail",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivilegedMail>;
    getContractAt(
      name: "IGnosisSafe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGnosisSafe>;
    getContractAt(
      name: "SafeChecker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeChecker>;
    getContractAt(
      name: "SafeDelegateHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeDelegateHelper>;

    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MailService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MailService>;
    deployContract(
      name: "MockSafe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSafe>;
    deployContract(
      name: "MockUSDC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDC>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "PrivilegedMail",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivilegedMail>;
    deployContract(
      name: "IGnosisSafe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGnosisSafe>;
    deployContract(
      name: "SafeChecker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeChecker>;
    deployContract(
      name: "SafeDelegateHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeDelegateHelper>;

    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MailService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MailService>;
    deployContract(
      name: "MockSafe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSafe>;
    deployContract(
      name: "MockUSDC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDC>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "PrivilegedMail",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivilegedMail>;
    deployContract(
      name: "IGnosisSafe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGnosisSafe>;
    deployContract(
      name: "SafeChecker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeChecker>;
    deployContract(
      name: "SafeDelegateHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeDelegateHelper>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
